/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lafargeholcim.planb.view;

/**
 *
 * @author AI-Saac
 */
public class Maintainance extends javax.swing.JFrame {

    /**
     * Creates new form MaintainanceForm
     */
    public Maintainance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        detailLabel = new javax.swing.JLabel();
        commentsLabel = new javax.swing.JLabel();
        idValueTextField = new javax.swing.JTextField();
        detailScrollPane = new javax.swing.JScrollPane();
        detailTextArea = new javax.swing.JTextArea();
        commentsScrollPane = new javax.swing.JScrollPane();
        commentsTextArea = new javax.swing.JTextArea();
        responsibleLabel = new javax.swing.JLabel();
        ownerComboBox = new javax.swing.JComboBox<>();
        startDateLabel = new javax.swing.JLabel();
        dueDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        cancellButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        progressLabel = new javax.swing.JLabel();
        progressValueLabel = new javax.swing.JLabel();
        progressSlider = new javax.swing.JSlider();
        statusTextField = new javax.swing.JTextField();
        durationLabel = new javax.swing.JLabel();
        durationValueLabel = new javax.swing.JLabel();
        daysLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        idLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        idLabel.setText("ID");
        getContentPane().add(idLabel, java.awt.BorderLayout.CENTER);

        detailLabel.setBackground(new java.awt.Color(48, 49, 50));
        detailLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        detailLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        detailLabel.setText("Detail");
        getContentPane().add(detailLabel, java.awt.BorderLayout.PAGE_START);

        commentsLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        commentsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        commentsLabel.setText("Comments");
        getContentPane().add(commentsLabel, java.awt.BorderLayout.PAGE_END);

        idValueTextField.setBackground(new java.awt.Color(60, 63, 65));
        idValueTextField.setForeground(javax.swing.UIManager.getDefaults().getColor("Table.selectionBackground"));
        idValueTextField.setText("Auto-Generated");
        getContentPane().add(idValueTextField, java.awt.BorderLayout.LINE_END);

        detailScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        detailTextArea.setColumns(20);
        detailTextArea.setLineWrap(true);
        detailTextArea.setRows(5);
        detailTextArea.setTabSize(0);
        detailTextArea.setText("uo tengo que ");
        detailTextArea.setWrapStyleWord(true);
        detailScrollPane.setViewportView(detailTextArea);

        getContentPane().add(detailScrollPane, java.awt.BorderLayout.LINE_START);

        commentsTextArea.setColumns(20);
        commentsTextArea.setRows(5);
        commentsScrollPane.setViewportView(commentsTextArea);

        getContentPane().add(commentsScrollPane, java.awt.BorderLayout.CENTER);

        responsibleLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        responsibleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        responsibleLabel.setText("Responsible");
        getContentPane().add(responsibleLabel, java.awt.BorderLayout.CENTER);

        ownerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SERGIO ORJUELA R", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ownerComboBox, java.awt.BorderLayout.CENTER);

        startDateLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        startDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        startDateLabel.setText("Start Date");
        getContentPane().add(startDateLabel, java.awt.BorderLayout.CENTER);

        dueDateLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dueDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dueDateLabel.setText("Due  Date");
        getContentPane().add(dueDateLabel, java.awt.BorderLayout.CENTER);

        endDateLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        endDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        endDateLabel.setText("End  Date");
        getContentPane().add(endDateLabel, java.awt.BorderLayout.CENTER);

        addButton.setText("ADD");
        getContentPane().add(addButton, java.awt.BorderLayout.CENTER);

        cancellButton.setText("CANCELL");
        getContentPane().add(cancellButton, java.awt.BorderLayout.CENTER);

        statusLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        statusLabel.setText("Status");
        getContentPane().add(statusLabel, java.awt.BorderLayout.CENTER);

        progressLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        progressLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        progressLabel.setText("Progress");
        getContentPane().add(progressLabel, java.awt.BorderLayout.CENTER);

        progressValueLabel.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        progressValueLabel.setForeground(new java.awt.Color(0, 51, 255));
        progressValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progressValueLabel.setText("100%");
        progressValueLabel.setOpaque(true);
        getContentPane().add(progressValueLabel, java.awt.BorderLayout.CENTER);

        progressSlider.setValue(0);
        getContentPane().add(progressSlider, java.awt.BorderLayout.CENTER);

        statusTextField.setText("IN_PROCESS");
        getContentPane().add(statusTextField, java.awt.BorderLayout.CENTER);

        durationLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        durationLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        durationLabel.setText("Duration");
        getContentPane().add(durationLabel, java.awt.BorderLayout.CENTER);

        durationValueLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        durationValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        durationValueLabel.setText("100");
        getContentPane().add(durationValueLabel, java.awt.BorderLayout.CENTER);

        daysLabel.setText("days");
        getContentPane().add(daysLabel, java.awt.BorderLayout.CENTER);

        jTable1.setForeground(java.awt.SystemColor.controlShadow);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maintainance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maintainance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maintainance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maintainance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maintainance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancellButton;
    private javax.swing.JLabel commentsLabel;
    private javax.swing.JScrollPane commentsScrollPane;
    private javax.swing.JTextArea commentsTextArea;
    private javax.swing.JLabel daysLabel;
    private javax.swing.JLabel detailLabel;
    private javax.swing.JScrollPane detailScrollPane;
    private javax.swing.JTextArea detailTextArea;
    private javax.swing.JLabel dueDateLabel;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JLabel durationValueLabel;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idValueTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> ownerComboBox;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JSlider progressSlider;
    private javax.swing.JLabel progressValueLabel;
    private javax.swing.JLabel responsibleLabel;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField statusTextField;
    // End of variables declaration//GEN-END:variables
}
