/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lafargeholcim.planb.view;

/**
 *
 * @author AI-Saac
 */
public class Meetings extends javax.swing.JFrame {

    /**
     * Creates new form Meetings
     */
    public Meetings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        meetingsPanel = new javax.swing.JPanel();
        optionTitlePanel = new javax.swing.JPanel();
        optionTitle = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        systemTitle = new javax.swing.JLabel();
        meetingContentPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        addMeetingLabel = new javax.swing.JLabel();
        meetingsListLabel = new javax.swing.JLabel();
        editMeetingLabel = new javax.swing.JLabel();
        meetinglistScrollPane1 = new javax.swing.JScrollPane();
        meetingListTable1 = new javax.swing.JTable();
        removeMeetingLabel = new javax.swing.JLabel();
        meetingInfoPanel = new javax.swing.JPanel();
        identifierLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        meetingNameLabel = new javax.swing.JLabel();
        actionPlanIdLabel = new javax.swing.JLabel();
        actionPlanTextFieldl = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        acronymLabel = new javax.swing.JLabel();
        acronymTextField = new javax.swing.JTextField();
        facilityLabel = new javax.swing.JLabel();
        facilityTextField = new javax.swing.JTextField();
        purposeLabel = new javax.swing.JLabel();
        purposeScrollPane = new javax.swing.JScrollPane();
        purposeTextArea = new javax.swing.JTextArea();
        apOwnerLabel = new javax.swing.JLabel();
        apOwnerTextField = new javax.swing.JTextField();
        rightPanel = new javax.swing.JPanel();
        workTeamInformationPanel = new javax.swing.JPanel();
        workTeamIdLabel = new javax.swing.JLabel();
        workTeamIdTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        workTeamIdTextField1 = new javax.swing.JTextField();
        totalTeamLabel = new javax.swing.JLabel();
        actionsTitleLabel = new javax.swing.JLabel();
        actionsSeparator = new javax.swing.JSeparator();
        appTeamLabel = new javax.swing.JLabel();
        totalTeamTextField = new javax.swing.JTextField();
        appTeamTextField = new javax.swing.JTextField();
        completedTeamLabel = new javax.swing.JLabel();
        completedTeamTextField = new javax.swing.JTextField();
        overdueTeamLabel = new javax.swing.JLabel();
        overdueTeamTextField = new javax.swing.JTextField();
        teamListLabel = new javax.swing.JLabel();
        removeMemberLabel = new javax.swing.JLabel();
        addMemberLabel = new javax.swing.JLabel();
        teamlistScrollPane = new javax.swing.JScrollPane();
        teamListTable = new javax.swing.JTable();
        teamListLabel1 = new javax.swing.JLabel();
        removeMemberLabel1 = new javax.swing.JLabel();
        addMemberLabel1 = new javax.swing.JLabel();
        adtParticipantsScrollPane = new javax.swing.JScrollPane();
        adtParticipantsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));

        meetingsPanel.setLayout(new java.awt.BorderLayout());

        optionTitlePanel.setBackground(new java.awt.Color(69, 73, 74));
        optionTitlePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 4, 8, new java.awt.Color(60, 63, 65)));
        optionTitlePanel.setMaximumSize(new java.awt.Dimension(32857, 65));
        optionTitlePanel.setMinimumSize(new java.awt.Dimension(90, 45));
        optionTitlePanel.setPreferredSize(new java.awt.Dimension(824, 45));
        optionTitlePanel.setLayout(new javax.swing.BoxLayout(optionTitlePanel, javax.swing.BoxLayout.LINE_AXIS));

        optionTitle.setForeground(new java.awt.Color(252, 254, 252));
        optionTitle.setText(" Meetings");
        optionTitlePanel.add(optionTitle);
        optionTitlePanel.add(filler1);

        systemTitle.setForeground(new java.awt.Color(252, 254, 252));
        systemTitle.setText("User: joel  ");
        optionTitlePanel.add(systemTitle);

        meetingsPanel.add(optionTitlePanel, java.awt.BorderLayout.NORTH);

        meetingContentPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 8, 4, 8, new java.awt.Color(60, 63, 65)));
        meetingContentPanel.setLayout(new javax.swing.BoxLayout(meetingContentPanel, javax.swing.BoxLayout.LINE_AXIS));

        leftPanel.setPreferredSize(new java.awt.Dimension(350, 500));

        addMeetingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plusWhite24.png"))); // NOI18N
        addMeetingLabel.setIconTextGap(0);

        meetingsListLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        meetingsListLabel.setText("Meetings List");
        meetingsListLabel.setIconTextGap(0);

        editMeetingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editWhite24.png"))); // NOI18N
        editMeetingLabel.setIconTextGap(0);

        meetingListTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        meetingListTable1.setColumnSelectionAllowed(true);
        meetingListTable1.setRowHeight(25);
        meetingListTable1.setShowVerticalLines(false);
        meetinglistScrollPane1.setViewportView(meetingListTable1);
        meetingListTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (meetingListTable1.getColumnModel().getColumnCount() > 0) {
            meetingListTable1.getColumnModel().getColumn(0).setMinWidth(65);
            meetingListTable1.getColumnModel().getColumn(0).setPreferredWidth(65);
            meetingListTable1.getColumnModel().getColumn(0).setMaxWidth(65);
        }

        removeMeetingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteWhite24.png"))); // NOI18N
        removeMeetingLabel.setIconTextGap(0);

        meetingInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Meeting Inforrmation", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        meetingInfoPanel.setPreferredSize(new java.awt.Dimension(340, 291));

        identifierLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        identifierLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        identifierLabel.setText("Identifier");
        identifierLabel.setIconTextGap(0);

        idTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idTextField.setText(" 1");

        meetingNameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        meetingNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        meetingNameLabel.setText("Name");
        meetingNameLabel.setIconTextGap(0);

        actionPlanIdLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        actionPlanIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actionPlanIdLabel.setText("Action Plan ID");
        actionPlanIdLabel.setIconTextGap(0);

        actionPlanTextFieldl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        actionPlanTextFieldl.setText(" 1");

        nameTextField.setText("Cómite Técnico Semanal");

        acronymLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        acronymLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acronymLabel.setText("Acronym");

        acronymTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        acronymTextField.setText("CTE");

        facilityLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        facilityLabel.setText("Facility");

        facilityTextField.setText("Planta Guayaquil");

        purposeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        purposeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purposeLabel.setText("Purpose");

        purposeTextArea.setEditable(false);
        purposeTextArea.setColumns(20);
        purposeTextArea.setLineWrap(true);
        purposeTextArea.setRows(5);
        purposeTextArea.setText("El propósito será siempre el mismo\nustedes ya saben como son este tipo\nde cosas\n");
        purposeTextArea.setWrapStyleWord(true);
        purposeScrollPane.setViewportView(purposeTextArea);

        apOwnerLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        apOwnerLabel.setText("Action Plan Owner");
        apOwnerLabel.setToolTipText("");

        apOwnerTextField.setText("SERGIO ORJUELA");

        javax.swing.GroupLayout meetingInfoPanelLayout = new javax.swing.GroupLayout(meetingInfoPanel);
        meetingInfoPanel.setLayout(meetingInfoPanelLayout);
        meetingInfoPanelLayout.setHorizontalGroup(
            meetingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meetingInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(meetingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(meetingInfoPanelLayout.createSequentialGroup()
                        .addComponent(apOwnerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(apOwnerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(meetingInfoPanelLayout.createSequentialGroup()
                        .addGroup(meetingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(acronymLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(meetingNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(identifierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(meetingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(meetingInfoPanelLayout.createSequentialGroup()
                                .addComponent(acronymTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(facilityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facilityTextField))
                            .addGroup(meetingInfoPanelLayout.createSequentialGroup()
                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(actionPlanIdLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(actionPlanTextFieldl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameTextField)))
                    .addGroup(meetingInfoPanelLayout.createSequentialGroup()
                        .addComponent(purposeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purposeScrollPane)))
                .addGap(12, 12, 12))
        );
        meetingInfoPanelLayout.setVerticalGroup(
            meetingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meetingInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(meetingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identifierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(meetingInfoPanelLayout.createSequentialGroup()
                        .addGroup(meetingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actionPlanTextFieldl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(actionPlanIdLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(meetingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(meetingNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(meetingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(acronymLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(meetingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(acronymTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(facilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(facilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(meetingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(purposeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purposeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(meetingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apOwnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apOwnerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meetinglistScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(meetingsListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(addMeetingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editMeetingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeMeetingLabel)))
                .addGap(51, 51, 51))
            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(leftPanelLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(meetingInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(meetingsListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMeetingLabel)
                    .addComponent(editMeetingLabel)
                    .addComponent(removeMeetingLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meetinglistScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                    .addContainerGap(203, Short.MAX_VALUE)
                    .addComponent(meetingInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        meetingContentPanel.add(leftPanel);

        rightPanel.setPreferredSize(new java.awt.Dimension(350, 500));

        workTeamInformationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("WorkTeam Information"));
        workTeamInformationPanel.setPreferredSize(new java.awt.Dimension(340, 211));

        workTeamIdLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        workTeamIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        workTeamIdLabel.setText("Identifier");
        workTeamIdLabel.setIconTextGap(0);

        workTeamIdTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        workTeamIdTextField.setText(" 1");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Performance");

        workTeamIdTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        workTeamIdTextField1.setText(" 1");

        totalTeamLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalTeamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalTeamLabel.setText("Total");
        totalTeamLabel.setIconTextGap(0);

        actionsTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        actionsTitleLabel.setText("Actions");

        actionsSeparator.setBackground(new java.awt.Color(187, 187, 187));

        appTeamLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        appTeamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appTeamLabel.setText("Completed APP");
        appTeamLabel.setIconTextGap(0);

        totalTeamTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalTeamTextField.setText(" 1");

        appTeamTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        appTeamTextField.setText(" 1");

        completedTeamLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        completedTeamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completedTeamLabel.setText("Completed");
        completedTeamLabel.setIconTextGap(0);

        completedTeamTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        completedTeamTextField.setText(" 1");

        overdueTeamLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        overdueTeamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        overdueTeamLabel.setText("Overdue");
        overdueTeamLabel.setIconTextGap(0);

        overdueTeamTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        overdueTeamTextField.setText(" 1");

        javax.swing.GroupLayout workTeamInformationPanelLayout = new javax.swing.GroupLayout(workTeamInformationPanel);
        workTeamInformationPanel.setLayout(workTeamInformationPanelLayout);
        workTeamInformationPanelLayout.setHorizontalGroup(
            workTeamInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workTeamInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workTeamInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workTeamInformationPanelLayout.createSequentialGroup()
                        .addGroup(workTeamInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(workTeamInformationPanelLayout.createSequentialGroup()
                                .addGroup(workTeamInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(workTeamIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(totalTeamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(workTeamInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(workTeamInformationPanelLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(workTeamIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel3)
                                        .addGap(12, 12, 12)
                                        .addComponent(workTeamIdTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 1, Short.MAX_VALUE))
                                    .addGroup(workTeamInformationPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalTeamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(appTeamLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(appTeamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(workTeamInformationPanelLayout.createSequentialGroup()
                                .addComponent(actionsTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(actionsSeparator)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(workTeamInformationPanelLayout.createSequentialGroup()
                        .addComponent(completedTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(completedTeamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(overdueTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(overdueTeamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        workTeamInformationPanelLayout.setVerticalGroup(
            workTeamInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workTeamInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workTeamInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(workTeamInformationPanelLayout.createSequentialGroup()
                        .addGroup(workTeamInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(workTeamIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(workTeamInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(workTeamIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(workTeamIdTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(actionsTitleLabel))
                    .addComponent(actionsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(workTeamInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTeamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appTeamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(workTeamInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completedTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(completedTeamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overdueTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overdueTeamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        teamListLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        teamListLabel.setText("Team Members List");
        teamListLabel.setIconTextGap(0);

        removeMemberLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteWhite24.png"))); // NOI18N
        removeMemberLabel.setIconTextGap(0);

        addMemberLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plusWhite24.png"))); // NOI18N
        addMemberLabel.setIconTextGap(0);

        teamListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Names"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teamListTable.setRowHeight(25);
        teamListTable.setShowVerticalLines(false);
        teamlistScrollPane.setViewportView(teamListTable);
        teamListTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (teamListTable.getColumnModel().getColumnCount() > 0) {
            teamListTable.getColumnModel().getColumn(0).setMinWidth(65);
            teamListTable.getColumnModel().getColumn(0).setPreferredWidth(65);
            teamListTable.getColumnModel().getColumn(0).setMaxWidth(65);
        }

        teamListLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        teamListLabel1.setText("Aditional Participants List");
        teamListLabel1.setIconTextGap(0);

        removeMemberLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteWhite24.png"))); // NOI18N
        removeMemberLabel1.setIconTextGap(0);

        addMemberLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plusWhite24.png"))); // NOI18N
        addMemberLabel1.setIconTextGap(0);

        adtParticipantsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Names"
            }
        ));
        adtParticipantsTable.setRowHeight(25);
        adtParticipantsTable.setShowVerticalLines(false);
        adtParticipantsScrollPane.setViewportView(adtParticipantsTable);
        if (adtParticipantsTable.getColumnModel().getColumnCount() > 0) {
            adtParticipantsTable.getColumnModel().getColumn(0).setMinWidth(65);
            adtParticipantsTable.getColumnModel().getColumn(0).setPreferredWidth(65);
            adtParticipantsTable.getColumnModel().getColumn(0).setMaxWidth(65);
        }

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(workTeamInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addComponent(teamListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addMemberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeMemberLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                        .addComponent(teamListLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addMemberLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeMemberLabel1))
                    .addComponent(teamlistScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(adtParticipantsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(workTeamInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(teamListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMemberLabel)
                    .addComponent(removeMemberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamlistScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(teamListLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMemberLabel1)
                    .addComponent(removeMemberLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adtParticipantsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        meetingContentPanel.add(rightPanel);

        meetingsPanel.add(meetingContentPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(meetingsPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meetings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meetings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meetings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meetings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meetings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acronymLabel;
    private javax.swing.JTextField acronymTextField;
    private javax.swing.JLabel actionPlanIdLabel;
    private javax.swing.JTextField actionPlanTextFieldl;
    private javax.swing.JSeparator actionsSeparator;
    private javax.swing.JLabel actionsTitleLabel;
    private javax.swing.JLabel addMeetingLabel;
    private javax.swing.JLabel addMemberLabel;
    private javax.swing.JLabel addMemberLabel1;
    private javax.swing.JScrollPane adtParticipantsScrollPane;
    private javax.swing.JTable adtParticipantsTable;
    private javax.swing.JLabel apOwnerLabel;
    private javax.swing.JTextField apOwnerTextField;
    private javax.swing.JLabel appTeamLabel;
    private javax.swing.JTextField appTeamTextField;
    private javax.swing.JLabel completedTeamLabel;
    private javax.swing.JTextField completedTeamTextField;
    private javax.swing.JLabel editMeetingLabel;
    private javax.swing.JLabel facilityLabel;
    private javax.swing.JTextField facilityTextField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel identifierLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel meetingContentPanel;
    private javax.swing.JPanel meetingInfoPanel;
    private javax.swing.JTable meetingListTable1;
    private javax.swing.JLabel meetingNameLabel;
    private javax.swing.JScrollPane meetinglistScrollPane1;
    private javax.swing.JLabel meetingsListLabel;
    private javax.swing.JPanel meetingsPanel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel optionTitle;
    private javax.swing.JPanel optionTitlePanel;
    private javax.swing.JLabel overdueTeamLabel;
    private javax.swing.JTextField overdueTeamTextField;
    private javax.swing.JLabel purposeLabel;
    private javax.swing.JScrollPane purposeScrollPane;
    private javax.swing.JTextArea purposeTextArea;
    private javax.swing.JLabel removeMeetingLabel;
    private javax.swing.JLabel removeMemberLabel;
    private javax.swing.JLabel removeMemberLabel1;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel systemTitle;
    private javax.swing.JLabel teamListLabel;
    private javax.swing.JLabel teamListLabel1;
    private javax.swing.JTable teamListTable;
    private javax.swing.JScrollPane teamlistScrollPane;
    private javax.swing.JLabel totalTeamLabel;
    private javax.swing.JTextField totalTeamTextField;
    private javax.swing.JLabel workTeamIdLabel;
    private javax.swing.JTextField workTeamIdTextField;
    private javax.swing.JTextField workTeamIdTextField1;
    private javax.swing.JPanel workTeamInformationPanel;
    // End of variables declaration//GEN-END:variables
}
