/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lafargeholcim.planb.view;

/**
 *
 * @author AI-Saac
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        apPanel = new javax.swing.JPanel();
        actionLabel = new javax.swing.JLabel();
        planLabel = new javax.swing.JLabel();
        meetingNamePanel = new javax.swing.JPanel();
        meetingLabel = new javax.swing.JLabel();
        title1Label = new javax.swing.JLabel();
        title2Label = new javax.swing.JLabel();
        dotMenuLabel = new javax.swing.JLabel();
        ownerNamePanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        surNameLabel = new javax.swing.JLabel();
        ownerLabel = new javax.swing.JLabel();
        participantsPanel = new javax.swing.JPanel();
        participantsLabel = new javax.swing.JLabel();
        scrollParctipants = new javax.swing.JScrollPane();
        participantsTextArea = new javax.swing.JTextArea();
        totalActionsPanel = new javax.swing.JPanel();
        actionsLabel = new javax.swing.JLabel();
        actionValueLabel = new javax.swing.JLabel();
        completedActionPanel = new javax.swing.JPanel();
        completedLabel = new javax.swing.JLabel();
        completedValueLabel = new javax.swing.JLabel();
        appActionPanel = new javax.swing.JPanel();
        appLabel = new javax.swing.JLabel();
        appValueLabel = new javax.swing.JLabel();
        overdueActionPanel = new javax.swing.JPanel();
        overdueLabel = new javax.swing.JLabel();
        overdueValueLabel = new javax.swing.JLabel();
        teamPerformancePanel = new javax.swing.JPanel();
        performanceLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        planExecutionPanel = new javax.swing.JPanel();
        executionLabel = new javax.swing.JLabel();
        executionValueLabel = new javax.swing.JLabel();
        datePanel = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        dateValueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(2147483647, 400));
        setMinimumSize(new java.awt.Dimension(230, 190));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1002, 190));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        apPanel.setBackground(new java.awt.Color(0, 66, 118));
        apPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 2, new java.awt.Color(252, 254, 252)));
        apPanel.setMaximumSize(new java.awt.Dimension(154, 190));
        apPanel.setMinimumSize(new java.awt.Dimension(0, 190));
        apPanel.setPreferredSize(new java.awt.Dimension(154, 190));

        actionLabel.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        actionLabel.setForeground(new java.awt.Color(252, 254, 252));
        actionLabel.setText("Action");

        planLabel.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        planLabel.setForeground(new java.awt.Color(252, 254, 252));
        planLabel.setText("Plan");

        javax.swing.GroupLayout apPanelLayout = new javax.swing.GroupLayout(apPanel);
        apPanel.setLayout(apPanelLayout);
        apPanelLayout.setHorizontalGroup(
            apPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(apPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionLabel)
                    .addComponent(planLabel))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        apPanelLayout.setVerticalGroup(
            apPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planLabel)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(apPanel, gridBagConstraints);

        meetingNamePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 2, 2, 2, new java.awt.Color(252, 254, 252)));
        meetingNamePanel.setMaximumSize(new java.awt.Dimension(32767, 95));
        meetingNamePanel.setMinimumSize(new java.awt.Dimension(252, 95));
        meetingNamePanel.setPreferredSize(new java.awt.Dimension(252, 95));

        meetingLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        meetingLabel.setText("meeting");

        title1Label.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        title1Label.setForeground(new java.awt.Color(252, 254, 252));
        title1Label.setText("Comité");

        title2Label.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        title2Label.setForeground(new java.awt.Color(252, 254, 252));
        title2Label.setText("Técnico");

        dotMenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dotsMenu-24.png"))); // NOI18N
        dotMenuLabel.setIconTextGap(0);

        javax.swing.GroupLayout meetingNamePanelLayout = new javax.swing.GroupLayout(meetingNamePanel);
        meetingNamePanel.setLayout(meetingNamePanelLayout);
        meetingNamePanelLayout.setHorizontalGroup(
            meetingNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meetingNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(meetingNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, meetingNamePanelLayout.createSequentialGroup()
                        .addComponent(title1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(meetingLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, meetingNamePanelLayout.createSequentialGroup()
                        .addGap(0, 37, Short.MAX_VALUE)
                        .addComponent(title2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(dotMenuLabel)))
                .addContainerGap())
        );
        meetingNamePanelLayout.setVerticalGroup(
            meetingNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meetingNamePanelLayout.createSequentialGroup()
                .addGroup(meetingNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(meetingNamePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title1Label))
                    .addComponent(meetingLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(meetingNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title2Label)
                    .addComponent(dotMenuLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        title2Label.getAccessibleContext().setAccessibleName("Indicadores");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(meetingNamePanel, gridBagConstraints);

        ownerNamePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 4, 2, new java.awt.Color(252, 254, 252)));
        ownerNamePanel.setMaximumSize(new java.awt.Dimension(32767, 95));
        ownerNamePanel.setMinimumSize(new java.awt.Dimension(126, 95));
        ownerNamePanel.setPreferredSize(new java.awt.Dimension(126, 95));

        firstNameLabel.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(252, 254, 252));
        firstNameLabel.setText("SERGIO");

        surNameLabel.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        surNameLabel.setForeground(new java.awt.Color(252, 254, 252));
        surNameLabel.setText("ORJUELA");

        ownerLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ownerLabel.setText("owner");

        javax.swing.GroupLayout ownerNamePanelLayout = new javax.swing.GroupLayout(ownerNamePanel);
        ownerNamePanel.setLayout(ownerNamePanelLayout);
        ownerNamePanelLayout.setHorizontalGroup(
            ownerNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ownerNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ownerNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(surNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ownerNamePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ownerLabel)))
                .addContainerGap())
        );
        ownerNamePanelLayout.setVerticalGroup(
            ownerNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ownerNamePanelLayout.createSequentialGroup()
                .addComponent(ownerLabel)
                .addGap(7, 7, 7)
                .addComponent(firstNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(surNameLabel)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(ownerNamePanel, gridBagConstraints);

        participantsPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(252, 254, 252)));
        participantsPanel.setMaximumSize(new java.awt.Dimension(32767, 95));
        participantsPanel.setMinimumSize(new java.awt.Dimension(126, 95));
        participantsPanel.setPreferredSize(new java.awt.Dimension(126, 95));

        participantsLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        participantsLabel.setText("participants");

        scrollParctipants.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 0));
        scrollParctipants.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        participantsTextArea.setEditable(false);
        participantsTextArea.setBackground(new java.awt.Color(60, 63, 65));
        participantsTextArea.setColumns(16);
        participantsTextArea.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        participantsTextArea.setForeground(new java.awt.Color(252, 254, 252));
        participantsTextArea.setLineWrap(true);
        participantsTextArea.setRows(3);
        participantsTextArea.setTabSize(0);
        participantsTextArea.setText("SOR, WCO, HRI, DCE, OMA, MCI, RCP, CRO, JOA, MDM");
        participantsTextArea.setWrapStyleWord(true);
        participantsTextArea.setAutoscrolls(false);
        participantsTextArea.setBorder(null);
        participantsTextArea.setPreferredSize(new java.awt.Dimension(120, 52));
        scrollParctipants.setViewportView(participantsTextArea);

        javax.swing.GroupLayout participantsPanelLayout = new javax.swing.GroupLayout(participantsPanel);
        participantsPanel.setLayout(participantsPanelLayout);
        participantsPanelLayout.setHorizontalGroup(
            participantsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(participantsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(participantsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollParctipants, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, participantsPanelLayout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addComponent(participantsLabel)))
                .addContainerGap())
        );
        participantsPanelLayout.setVerticalGroup(
            participantsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(participantsPanelLayout.createSequentialGroup()
                .addComponent(participantsLabel)
                .addGap(4, 4, 4)
                .addComponent(scrollParctipants, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(participantsPanel, gridBagConstraints);

        totalActionsPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(252, 254, 252)));
        totalActionsPanel.setMaximumSize(new java.awt.Dimension(32767, 95));
        totalActionsPanel.setMinimumSize(new java.awt.Dimension(100, 95));
        totalActionsPanel.setPreferredSize(new java.awt.Dimension(100, 95));

        actionsLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        actionsLabel.setText("actions");

        actionValueLabel.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        actionValueLabel.setForeground(new java.awt.Color(252, 254, 252));
        actionValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actionValueLabel.setText("100");

        javax.swing.GroupLayout totalActionsPanelLayout = new javax.swing.GroupLayout(totalActionsPanel);
        totalActionsPanel.setLayout(totalActionsPanelLayout);
        totalActionsPanelLayout.setHorizontalGroup(
            totalActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalActionsPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(actionValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(4, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalActionsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actionsLabel)
                .addContainerGap())
        );
        totalActionsPanelLayout.setVerticalGroup(
            totalActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalActionsPanelLayout.createSequentialGroup()
                .addComponent(actionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel1.add(totalActionsPanel, gridBagConstraints);

        completedActionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(252, 254, 252)));
        completedActionPanel.setMaximumSize(new java.awt.Dimension(32767, 95));
        completedActionPanel.setMinimumSize(new java.awt.Dimension(0, 95));
        completedActionPanel.setPreferredSize(new java.awt.Dimension(100, 95));

        completedLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        completedLabel.setText("completed");

        completedValueLabel.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        completedValueLabel.setForeground(new java.awt.Color(252, 254, 252));
        completedValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completedValueLabel.setText("40");
        completedValueLabel.setMaximumSize(new java.awt.Dimension(69, 54));
        completedValueLabel.setMinimumSize(new java.awt.Dimension(69, 54));
        completedValueLabel.setPreferredSize(new java.awt.Dimension(69, 54));

        javax.swing.GroupLayout completedActionPanelLayout = new javax.swing.GroupLayout(completedActionPanel);
        completedActionPanel.setLayout(completedActionPanelLayout);
        completedActionPanelLayout.setHorizontalGroup(
            completedActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(completedActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, completedActionPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(completedLabel))
                    .addComponent(completedValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addContainerGap())
        );
        completedActionPanelLayout.setVerticalGroup(
            completedActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedActionPanelLayout.createSequentialGroup()
                .addComponent(completedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(completedValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        jPanel1.add(completedActionPanel, gridBagConstraints);

        appActionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(252, 254, 252)));
        appActionPanel.setMaximumSize(new java.awt.Dimension(32767, 95));
        appActionPanel.setMinimumSize(new java.awt.Dimension(100, 95));
        appActionPanel.setPreferredSize(new java.awt.Dimension(100, 95));

        appLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        appLabel.setText("app");

        appValueLabel.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        appValueLabel.setForeground(new java.awt.Color(252, 254, 252));
        appValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appValueLabel.setText("35");
        appValueLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout appActionPanelLayout = new javax.swing.GroupLayout(appActionPanel);
        appActionPanel.setLayout(appActionPanelLayout);
        appActionPanelLayout.setHorizontalGroup(
            appActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appActionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(appLabel)
                .addContainerGap())
            .addGroup(appActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        appActionPanelLayout.setVerticalGroup(
            appActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appActionPanelLayout.createSequentialGroup()
                .addComponent(appLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        jPanel1.add(appActionPanel, gridBagConstraints);

        overdueActionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(252, 254, 252)));
        overdueActionPanel.setMaximumSize(new java.awt.Dimension(32767, 95));
        overdueActionPanel.setMinimumSize(new java.awt.Dimension(100, 95));
        overdueActionPanel.setPreferredSize(new java.awt.Dimension(100, 95));

        overdueLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        overdueLabel.setText("overdue");

        overdueValueLabel.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        overdueValueLabel.setForeground(new java.awt.Color(252, 254, 252));
        overdueValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        overdueValueLabel.setText("15");

        javax.swing.GroupLayout overdueActionPanelLayout = new javax.swing.GroupLayout(overdueActionPanel);
        overdueActionPanel.setLayout(overdueActionPanelLayout);
        overdueActionPanelLayout.setHorizontalGroup(
            overdueActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overdueActionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(overdueLabel)
                .addContainerGap())
            .addGroup(overdueActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(overdueValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        overdueActionPanelLayout.setVerticalGroup(
            overdueActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overdueActionPanelLayout.createSequentialGroup()
                .addComponent(overdueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overdueValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        jPanel1.add(overdueActionPanel, gridBagConstraints);

        teamPerformancePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(252, 254, 252)));
        teamPerformancePanel.setMaximumSize(new java.awt.Dimension(32767, 95));
        teamPerformancePanel.setMinimumSize(new java.awt.Dimension(100, 95));
        teamPerformancePanel.setPreferredSize(new java.awt.Dimension(100, 95));

        performanceLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        performanceLabel.setText("performance");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 67, 68));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("65%");

        javax.swing.GroupLayout teamPerformancePanelLayout = new javax.swing.GroupLayout(teamPerformancePanel);
        teamPerformancePanel.setLayout(teamPerformancePanelLayout);
        teamPerformancePanelLayout.setHorizontalGroup(
            teamPerformancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamPerformancePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(performanceLabel)
                .addContainerGap())
            .addGroup(teamPerformancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        teamPerformancePanelLayout.setVerticalGroup(
            teamPerformancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamPerformancePanelLayout.createSequentialGroup()
                .addComponent(performanceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel1.add(teamPerformancePanel, gridBagConstraints);

        planExecutionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 4, new java.awt.Color(252, 254, 252)));
        planExecutionPanel.setMaximumSize(new java.awt.Dimension(32767, 95));
        planExecutionPanel.setMinimumSize(new java.awt.Dimension(100, 95));
        planExecutionPanel.setPreferredSize(new java.awt.Dimension(100, 95));

        executionLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        executionLabel.setText("execution");

        executionValueLabel.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        executionValueLabel.setForeground(new java.awt.Color(51, 255, 0));
        executionValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        executionValueLabel.setText("76%");

        javax.swing.GroupLayout planExecutionPanelLayout = new javax.swing.GroupLayout(planExecutionPanel);
        planExecutionPanel.setLayout(planExecutionPanelLayout);
        planExecutionPanelLayout.setHorizontalGroup(
            planExecutionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, planExecutionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(executionLabel)
                .addContainerGap())
            .addGroup(planExecutionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(executionValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(4, Short.MAX_VALUE))
        );
        planExecutionPanelLayout.setVerticalGroup(
            planExecutionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planExecutionPanelLayout.createSequentialGroup()
                .addComponent(executionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(executionValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        jPanel1.add(planExecutionPanel, gridBagConstraints);

        datePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 4, new java.awt.Color(252, 254, 252)));
        datePanel.setMaximumSize(new java.awt.Dimension(32767, 90));
        datePanel.setMinimumSize(new java.awt.Dimension(0, 90));
        datePanel.setPreferredSize(new java.awt.Dimension(200, 95));

        dateLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        dateLabel.setText("date");

        dateValueLabel.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        dateValueLabel.setForeground(new java.awt.Color(252, 254, 252));
        dateValueLabel.setText("2016-11-14");

        javax.swing.GroupLayout datePanelLayout = new javax.swing.GroupLayout(datePanel);
        datePanel.setLayout(datePanelLayout);
        datePanelLayout.setHorizontalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datePanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datePanelLayout.createSequentialGroup()
                        .addComponent(dateLabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datePanelLayout.createSequentialGroup()
                        .addComponent(dateValueLabel)
                        .addGap(16, 16, 16))))
        );
        datePanelLayout.setVerticalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datePanelLayout.createSequentialGroup()
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(datePanel, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionLabel;
    private javax.swing.JLabel actionValueLabel;
    private javax.swing.JLabel actionsLabel;
    private javax.swing.JPanel apPanel;
    private javax.swing.JPanel appActionPanel;
    private javax.swing.JLabel appLabel;
    private javax.swing.JLabel appValueLabel;
    private javax.swing.JPanel completedActionPanel;
    private javax.swing.JLabel completedLabel;
    private javax.swing.JLabel completedValueLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel datePanel;
    private javax.swing.JLabel dateValueLabel;
    private javax.swing.JLabel dotMenuLabel;
    private javax.swing.JLabel executionLabel;
    private javax.swing.JLabel executionValueLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel meetingLabel;
    private javax.swing.JPanel meetingNamePanel;
    private javax.swing.JPanel overdueActionPanel;
    private javax.swing.JLabel overdueLabel;
    private javax.swing.JLabel overdueValueLabel;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JPanel ownerNamePanel;
    private javax.swing.JLabel participantsLabel;
    private javax.swing.JPanel participantsPanel;
    private javax.swing.JTextArea participantsTextArea;
    private javax.swing.JLabel performanceLabel;
    private javax.swing.JPanel planExecutionPanel;
    private javax.swing.JLabel planLabel;
    private javax.swing.JScrollPane scrollParctipants;
    private javax.swing.JLabel surNameLabel;
    private javax.swing.JPanel teamPerformancePanel;
    private javax.swing.JLabel title1Label;
    private javax.swing.JLabel title2Label;
    private javax.swing.JPanel totalActionsPanel;
    // End of variables declaration//GEN-END:variables
}
