/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lafargeholcim.planb.view.design;

/**
 *
 * @author AI-Saac
 */
public class Maintainance extends javax.swing.JFrame {

    /**
     * Creates new form MaintainanceForm
     */
    public Maintainance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        idLabel = new javax.swing.JLabel();
        detailLabel = new javax.swing.JLabel();
        commentsLabel = new javax.swing.JLabel();
        idValueTextField = new javax.swing.JTextField();
        detailScrollPane = new javax.swing.JScrollPane();
        detailTextArea = new javax.swing.JTextArea();
        commentsScrollPane = new javax.swing.JScrollPane();
        commentsTextArea = new javax.swing.JTextArea();
        responsibleLabel = new javax.swing.JLabel();
        ownerComboBox = new javax.swing.JComboBox<>();
        startDateLabel = new javax.swing.JLabel();
        dueDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        cancellButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        progressLabel = new javax.swing.JLabel();
        progressValueLabel = new javax.swing.JLabel();
        progressSlider = new javax.swing.JSlider();
        statusTextField = new javax.swing.JTextField();
        durationLabel = new javax.swing.JLabel();
        durationValueLabel = new javax.swing.JLabel();
        daysLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        idLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        idLabel.setText("ID");

        detailLabel.setBackground(new java.awt.Color(48, 49, 50));
        detailLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        detailLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        detailLabel.setText("Detail");

        commentsLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        commentsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        commentsLabel.setText("Comments");

        idValueTextField.setBackground(new java.awt.Color(60, 63, 65));
        idValueTextField.setForeground(javax.swing.UIManager.getDefaults().getColor("Hyperlink.linkColor"));
        idValueTextField.setText("Auto-Generated");

        detailScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        detailTextArea.setColumns(20);
        detailTextArea.setLineWrap(true);
        detailTextArea.setRows(5);
        detailTextArea.setTabSize(0);
        detailTextArea.setText("uo tengo que ");
        detailTextArea.setWrapStyleWord(true);
        detailScrollPane.setViewportView(detailTextArea);

        commentsTextArea.setColumns(20);
        commentsTextArea.setRows(5);
        commentsScrollPane.setViewportView(commentsTextArea);

        responsibleLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        responsibleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        responsibleLabel.setText("Responsible");

        ownerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SERGIO ORJUELA R", "Item 2", "Item 3", "Item 4" }));

        startDateLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        startDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        startDateLabel.setText("Start Date");

        dueDateLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dueDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dueDateLabel.setText("Due  Date");

        endDateLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        endDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        endDateLabel.setText("End  Date");

        addButton.setText("ADD");

        cancellButton.setText("CANCELL");

        statusLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        statusLabel.setText("Status");

        progressLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        progressLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        progressLabel.setText("Progress");

        progressValueLabel.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        progressValueLabel.setForeground(new java.awt.Color(0, 51, 255));
        progressValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progressValueLabel.setText("100%");
        progressValueLabel.setOpaque(true);

        progressSlider.setValue(0);

        statusTextField.setText("IN_PROCESS");

        durationLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        durationLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        durationLabel.setText("Duration");

        durationValueLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        durationValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        durationValueLabel.setText("100");

        daysLabel.setText("days");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(startDateLabel)
            .addComponent(responsibleLabel)
            .addComponent(durationValueLabel)
            .addComponent(statusLabel)
            .addComponent(endDateLabel)
            .addComponent(idLabel)
            .addComponent(durationLabel)
            .addComponent(progressLabel)
            .addComponent(progressValueLabel)
            .addComponent(ownerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(dueDateLabel)
            .addGroup(layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(commentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(addButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(commentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detailScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(detailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancellButton)
                        .addGap(256, 256, 256)
                        .addComponent(daysLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(detailLabel)
                        .addGap(46, 46, 46)
                        .addComponent(daysLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(progressSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(commentsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(detailScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(commentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel)
                            .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateLabel)
                            .addComponent(responsibleLabel)
                            .addComponent(durationValueLabel)
                            .addComponent(statusLabel)
                            .addComponent(endDateLabel)
                            .addComponent(durationLabel)
                            .addComponent(progressLabel)
                            .addComponent(progressValueLabel)
                            .addComponent(ownerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dueDateLabel))
                        .addGap(74, 74, 74)
                        .addComponent(idValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancellButton)
                        .addGap(113, 113, 113))))
        );

        pack();
    }//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maintainance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maintainance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maintainance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maintainance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maintainance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancellButton;
    private javax.swing.JLabel commentsLabel;
    private javax.swing.JScrollPane commentsScrollPane;
    private javax.swing.JTextArea commentsTextArea;
    private javax.swing.JLabel daysLabel;
    private javax.swing.JLabel detailLabel;
    private javax.swing.JScrollPane detailScrollPane;
    private javax.swing.JTextArea detailTextArea;
    private javax.swing.JLabel dueDateLabel;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JLabel durationValueLabel;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idValueTextField;
    private javax.swing.JComboBox<String> ownerComboBox;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JSlider progressSlider;
    private javax.swing.JLabel progressValueLabel;
    private javax.swing.JLabel responsibleLabel;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField statusTextField;
    // End of variables declaration//GEN-END:variables
}
