/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lafargeholcim.planb.view.design;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author AI-Saac
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        meetingPopupMenu = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        apInformationPanel = new javax.swing.JPanel();
        apPanel = new javax.swing.JPanel();
        actionLabel = new javax.swing.JLabel();
        planLabel = new javax.swing.JLabel();
        meetingNamePanel = new javax.swing.JPanel();
        meetingLabel = new javax.swing.JLabel();
        title1Label = new javax.swing.JLabel();
        title2Label = new javax.swing.JLabel();
        dotMenuLabel = new javax.swing.JLabel();
        ownerNamePanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        ownerLabel = new javax.swing.JLabel();
        participantsPanel = new javax.swing.JPanel();
        participantsLabel = new javax.swing.JLabel();
        scrollParticipants = new javax.swing.JScrollPane();
        participantsTextArea = new javax.swing.JTextArea();
        totalActionsPanel = new javax.swing.JPanel();
        actionsLabel = new javax.swing.JLabel();
        actionValueLabel = new javax.swing.JLabel();
        completedActionPanel = new javax.swing.JPanel();
        completedLabel = new javax.swing.JLabel();
        completedValueLabel = new javax.swing.JLabel();
        appActionPanel = new javax.swing.JPanel();
        appLabel = new javax.swing.JLabel();
        appValueLabel = new javax.swing.JLabel();
        overdueActionPanel = new javax.swing.JPanel();
        overdueLabel = new javax.swing.JLabel();
        overdueValueLabel = new javax.swing.JLabel();
        teamPerformancePanel = new javax.swing.JPanel();
        performanceLabel = new javax.swing.JLabel();
        performanceValueLabel = new javax.swing.JLabel();
        planExecutionPanel = new javax.swing.JPanel();
        executionLabel = new javax.swing.JLabel();
        executionValueLabel = new javax.swing.JLabel();
        datePanel = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        dateValueLabel = new javax.swing.JLabel();
        filterLabelPanel = new javax.swing.JPanel();
        filterLabel = new javax.swing.JLabel();
        statusPanel = new javax.swing.JPanel();
        statusRadioButton = new javax.swing.JRadioButton();
        statusComboBox = new javax.swing.JComboBox<>();
        status2Label = new javax.swing.JLabel();
        dateRadioButton = new javax.swing.JRadioButton();
        dateComboBox = new javax.swing.JComboBox<>();
        date2Label = new javax.swing.JLabel();
        ownerRadioButton = new javax.swing.JRadioButton();
        owner2Label = new javax.swing.JLabel();
        owner2TextField = new javax.swing.JTextField();
        contentRadioButton = new javax.swing.JRadioButton();
        content2Label = new javax.swing.JLabel();
        hintTextField = new javax.swing.JTextField();
        buttonsPanel = new javax.swing.JPanel();
        addIcon = new javax.swing.JLabel();
        editIcon = new javax.swing.JLabel();
        deleteIcon = new javax.swing.JLabel();

        meetingPopupMenu.setAutoscrolls(true);

        jMenuItem1.setText("Indicadores");
        meetingPopupMenu.add(jMenuItem1);

        jMenuItem2.setText("Alternative and Raw M");
        jMenuItem2.setMinimumSize(new java.awt.Dimension(50, 20));
        meetingPopupMenu.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        apInformationPanel.setBackground(new java.awt.Color(252, 254, 252));
        apInformationPanel.setMinimumSize(new java.awt.Dimension(650, 250));
        apInformationPanel.setPreferredSize(new java.awt.Dimension(800, 250));
        apInformationPanel.setLayout(new java.awt.GridBagLayout());

        apPanel.setBackground(new java.awt.Color(0, 66, 118));
        apPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 2, new java.awt.Color(252, 254, 252)));
        apPanel.setMaximumSize(new java.awt.Dimension(164, 200));
        apPanel.setMinimumSize(new java.awt.Dimension(110, 200));
        apPanel.setPreferredSize(new java.awt.Dimension(120, 200));

        actionLabel.setFont(new java.awt.Font("Dialog", 1, 35)); // NOI18N
        actionLabel.setForeground(new java.awt.Color(252, 254, 252));
        actionLabel.setText("Action");

        planLabel.setFont(new java.awt.Font("Dialog", 1, 35)); // NOI18N
        planLabel.setForeground(new java.awt.Color(252, 254, 252));
        planLabel.setText("Plan");

        javax.swing.GroupLayout apPanelLayout = new javax.swing.GroupLayout(apPanel);
        apPanel.setLayout(apPanelLayout);
        apPanelLayout.setHorizontalGroup(
            apPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(apPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionLabel)
                    .addComponent(planLabel))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        apPanelLayout.setVerticalGroup(
            apPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planLabel)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        apInformationPanel.add(apPanel, gridBagConstraints);

        meetingNamePanel.setBackground(new java.awt.Color(48, 49, 50));
        meetingNamePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 2, 2, 2, new java.awt.Color(252, 254, 252)));
        meetingNamePanel.setMinimumSize(new java.awt.Dimension(242, 100));
        meetingNamePanel.setPreferredSize(new java.awt.Dimension(252, 100));

        meetingLabel.setBackground(new java.awt.Color(187, 187, 188));
        meetingLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        meetingLabel.setForeground(new java.awt.Color(252, 254, 252));
        meetingLabel.setText("meeting");

        title1Label.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        title1Label.setForeground(new java.awt.Color(252, 254, 252));
        title1Label.setText("Hola ");
        title1Label.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        title1Label.setIconTextGap(0);
        title1Label.setMaximumSize(new java.awt.Dimension(175, 34));
        title1Label.setMinimumSize(new java.awt.Dimension(0, 0));
        title1Label.setPreferredSize(new java.awt.Dimension(175, 34));

        title2Label.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        title2Label.setForeground(new java.awt.Color(252, 254, 252));
        title2Label.setText("tecnico tencdafoo");
        title2Label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        title2Label.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        title2Label.setIconTextGap(0);
        title2Label.setMaximumSize(new java.awt.Dimension(195, 37));
        title2Label.setMinimumSize(new java.awt.Dimension(157, 37));
        title2Label.setPreferredSize(new java.awt.Dimension(148, 37));

        dotMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dotMenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dotsMenu-24.png"))); // NOI18N
        dotMenuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dotMenuLabel.setIconTextGap(0);
        dotMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dotMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout meetingNamePanelLayout = new javax.swing.GroupLayout(meetingNamePanel);
        meetingNamePanel.setLayout(meetingNamePanelLayout);
        meetingNamePanelLayout.setHorizontalGroup(
            meetingNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meetingNamePanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(meetingNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(meetingNamePanelLayout.createSequentialGroup()
                        .addComponent(title1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(meetingLabel))
                    .addGroup(meetingNamePanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(title2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(dotMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        meetingNamePanelLayout.setVerticalGroup(
            meetingNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meetingNamePanelLayout.createSequentialGroup()
                .addGroup(meetingNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meetingLabel)
                    .addGroup(meetingNamePanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(title1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(meetingNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(dotMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        title2Label.getAccessibleContext().setAccessibleName("");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        apInformationPanel.add(meetingNamePanel, gridBagConstraints);

        ownerNamePanel.setBackground(new java.awt.Color(48, 49, 50));
        ownerNamePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 4, 2, new java.awt.Color(252, 254, 252)));
        ownerNamePanel.setMinimumSize(new java.awt.Dimension(121, 100));
        ownerNamePanel.setPreferredSize(new java.awt.Dimension(126, 100));

        firstNameLabel.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(252, 254, 252));
        firstNameLabel.setText("SERGIO");
        firstNameLabel.setIconTextGap(0);
        firstNameLabel.setMaximumSize(new java.awt.Dimension(90, 23));
        firstNameLabel.setMinimumSize(new java.awt.Dimension(90, 23));
        firstNameLabel.setPreferredSize(new java.awt.Dimension(90, 23));

        surnameLabel.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        surnameLabel.setForeground(new java.awt.Color(252, 254, 252));
        surnameLabel.setText("ORJUELA");
        surnameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        surnameLabel.setIconTextGap(0);
        surnameLabel.setMaximumSize(new java.awt.Dimension(90, 23));
        surnameLabel.setMinimumSize(new java.awt.Dimension(90, 23));
        surnameLabel.setPreferredSize(new java.awt.Dimension(90, 23));

        ownerLabel.setBackground(new java.awt.Color(187, 187, 188));
        ownerLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ownerLabel.setForeground(new java.awt.Color(252, 254, 252));
        ownerLabel.setText("owner");

        javax.swing.GroupLayout ownerNamePanelLayout = new javax.swing.GroupLayout(ownerNamePanel);
        ownerNamePanel.setLayout(ownerNamePanelLayout);
        ownerNamePanelLayout.setHorizontalGroup(
            ownerNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ownerNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ownerNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ownerNamePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ownerLabel))
                    .addGroup(ownerNamePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(surnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ownerNamePanelLayout.setVerticalGroup(
            ownerNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ownerNamePanelLayout.createSequentialGroup()
                .addComponent(ownerLabel)
                .addGap(4, 4, 4)
                .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(surnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        apInformationPanel.add(ownerNamePanel, gridBagConstraints);

        participantsPanel.setBackground(new java.awt.Color(48, 49, 50));
        participantsPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 4, 2, new java.awt.Color(252, 254, 252)));
        participantsPanel.setMinimumSize(new java.awt.Dimension(126, 100));
        participantsPanel.setPreferredSize(new java.awt.Dimension(126, 100));

        participantsLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        participantsLabel.setForeground(new java.awt.Color(252, 254, 252));
        participantsLabel.setText("participants");

        scrollParticipants.setBackground(new java.awt.Color(48, 49, 50));
        scrollParticipants.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 0));
        scrollParticipants.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollParticipants.setPreferredSize(new java.awt.Dimension(120, 48));

        participantsTextArea.setEditable(false);
        participantsTextArea.setBackground(new java.awt.Color(60, 63, 65));
        participantsTextArea.setColumns(16);
        participantsTextArea.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        participantsTextArea.setForeground(new java.awt.Color(252, 254, 252));
        participantsTextArea.setLineWrap(true);
        participantsTextArea.setRows(3);
        participantsTextArea.setTabSize(0);
        participantsTextArea.setText("SOR, WCO, HRI, DCE, OMA, MCI, RCP, CRO, JOA, MDM");
        participantsTextArea.setWrapStyleWord(true);
        participantsTextArea.setAutoscrolls(false);
        participantsTextArea.setBorder(null);
        participantsTextArea.setMinimumSize(new java.awt.Dimension(0, 150));
        participantsTextArea.setPreferredSize(new java.awt.Dimension(120, 52));
        scrollParticipants.setViewportView(participantsTextArea);

        javax.swing.GroupLayout participantsPanelLayout = new javax.swing.GroupLayout(participantsPanel);
        participantsPanel.setLayout(participantsPanelLayout);
        participantsPanelLayout.setHorizontalGroup(
            participantsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(participantsPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(participantsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollParticipants, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, participantsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(participantsLabel)))
                .addContainerGap())
        );
        participantsPanelLayout.setVerticalGroup(
            participantsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(participantsPanelLayout.createSequentialGroup()
                .addComponent(participantsLabel)
                .addGap(4, 4, 4)
                .addComponent(scrollParticipants, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        apInformationPanel.add(participantsPanel, gridBagConstraints);

        totalActionsPanel.setBackground(new java.awt.Color(230, 231, 234));
        totalActionsPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 2, 2, 2, new java.awt.Color(252, 254, 252)));
        totalActionsPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        totalActionsPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        actionsLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        actionsLabel.setForeground(new java.awt.Color(48, 49, 50));
        actionsLabel.setText("actions");

        actionValueLabel.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        actionValueLabel.setForeground(new java.awt.Color(122, 120, 123));
        actionValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actionValueLabel.setText("100");
        actionValueLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        actionValueLabel.setIconTextGap(0);

        javax.swing.GroupLayout totalActionsPanelLayout = new javax.swing.GroupLayout(totalActionsPanel);
        totalActionsPanel.setLayout(totalActionsPanelLayout);
        totalActionsPanelLayout.setHorizontalGroup(
            totalActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalActionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalActionsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(actionsLabel))
                    .addComponent(actionValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalActionsPanelLayout.setVerticalGroup(
            totalActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalActionsPanelLayout.createSequentialGroup()
                .addComponent(actionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        apInformationPanel.add(totalActionsPanel, gridBagConstraints);

        completedActionPanel.setBackground(new java.awt.Color(230, 231, 234));
        completedActionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 4, 2, new java.awt.Color(252, 254, 252)));
        completedActionPanel.setForeground(new java.awt.Color(230, 231, 234));
        completedActionPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        completedActionPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        completedLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        completedLabel.setForeground(new java.awt.Color(48, 49, 50));
        completedLabel.setText("completed");

        completedValueLabel.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        completedValueLabel.setForeground(new java.awt.Color(120, 120, 123));
        completedValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completedValueLabel.setText("40");
        completedValueLabel.setMaximumSize(new java.awt.Dimension(69, 54));
        completedValueLabel.setMinimumSize(new java.awt.Dimension(69, 54));
        completedValueLabel.setPreferredSize(new java.awt.Dimension(69, 54));

        javax.swing.GroupLayout completedActionPanelLayout = new javax.swing.GroupLayout(completedActionPanel);
        completedActionPanel.setLayout(completedActionPanelLayout);
        completedActionPanelLayout.setHorizontalGroup(
            completedActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(completedActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, completedActionPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(completedLabel))
                    .addComponent(completedValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addContainerGap())
        );
        completedActionPanelLayout.setVerticalGroup(
            completedActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedActionPanelLayout.createSequentialGroup()
                .addComponent(completedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(completedValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        apInformationPanel.add(completedActionPanel, gridBagConstraints);

        appActionPanel.setBackground(new java.awt.Color(230, 231, 234));
        appActionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 2, 2, 2, new java.awt.Color(252, 254, 252)));
        appActionPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        appActionPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        appLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        appLabel.setForeground(new java.awt.Color(48, 49, 50));
        appLabel.setText("app");

        appValueLabel.setBackground(new java.awt.Color(48, 49, 50));
        appValueLabel.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        appValueLabel.setForeground(new java.awt.Color(120, 120, 123));
        appValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appValueLabel.setText("35");
        appValueLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        appValueLabel.setIconTextGap(0);

        javax.swing.GroupLayout appActionPanelLayout = new javax.swing.GroupLayout(appActionPanel);
        appActionPanel.setLayout(appActionPanelLayout);
        appActionPanelLayout.setHorizontalGroup(
            appActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(appActionPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(appLabel))
                    .addComponent(appValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap())
        );
        appActionPanelLayout.setVerticalGroup(
            appActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appActionPanelLayout.createSequentialGroup()
                .addComponent(appLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        apInformationPanel.add(appActionPanel, gridBagConstraints);

        overdueActionPanel.setBackground(new java.awt.Color(230, 231, 234));
        overdueActionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 4, 2, new java.awt.Color(252, 254, 252)));
        overdueActionPanel.setMinimumSize(new java.awt.Dimension(100, 100));

        overdueLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        overdueLabel.setForeground(new java.awt.Color(48, 49, 50));
        overdueLabel.setText("overdue");

        overdueValueLabel.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        overdueValueLabel.setForeground(new java.awt.Color(120, 120, 123));
        overdueValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        overdueValueLabel.setText("15");
        overdueValueLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout overdueActionPanelLayout = new javax.swing.GroupLayout(overdueActionPanel);
        overdueActionPanel.setLayout(overdueActionPanelLayout);
        overdueActionPanelLayout.setHorizontalGroup(
            overdueActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overdueActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overdueActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overdueActionPanelLayout.createSequentialGroup()
                        .addGap(0, 146, Short.MAX_VALUE)
                        .addComponent(overdueLabel))
                    .addComponent(overdueValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        overdueActionPanelLayout.setVerticalGroup(
            overdueActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overdueActionPanelLayout.createSequentialGroup()
                .addComponent(overdueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overdueValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        apInformationPanel.add(overdueActionPanel, gridBagConstraints);

        teamPerformancePanel.setBackground(new java.awt.Color(254, 67, 68));
        teamPerformancePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 2, 2, 2, new java.awt.Color(252, 254, 252)));
        teamPerformancePanel.setMinimumSize(new java.awt.Dimension(110, 100));
        teamPerformancePanel.setPreferredSize(new java.awt.Dimension(110, 100));

        performanceLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        performanceLabel.setForeground(new java.awt.Color(252, 254, 252));
        performanceLabel.setText("performance");

        performanceValueLabel.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        performanceValueLabel.setForeground(new java.awt.Color(252, 254, 252));
        performanceValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        performanceValueLabel.setText("165%");
        performanceValueLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        performanceValueLabel.setIconTextGap(0);

        javax.swing.GroupLayout teamPerformancePanelLayout = new javax.swing.GroupLayout(teamPerformancePanel);
        teamPerformancePanel.setLayout(teamPerformancePanelLayout);
        teamPerformancePanelLayout.setHorizontalGroup(
            teamPerformancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamPerformancePanelLayout.createSequentialGroup()
                .addGroup(teamPerformancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teamPerformancePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(performanceLabel))
                    .addComponent(performanceValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );
        teamPerformancePanelLayout.setVerticalGroup(
            teamPerformancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamPerformancePanelLayout.createSequentialGroup()
                .addComponent(performanceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(performanceValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        apInformationPanel.add(teamPerformancePanel, gridBagConstraints);

        planExecutionPanel.setBackground(new java.awt.Color(48, 49, 50));
        planExecutionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 2, 2, 4, new java.awt.Color(252, 254, 252)));
        planExecutionPanel.setMinimumSize(new java.awt.Dimension(110, 100));
        planExecutionPanel.setPreferredSize(new java.awt.Dimension(110, 100));

        executionLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        executionLabel.setForeground(new java.awt.Color(252, 254, 252));
        executionLabel.setText("execution");

        executionValueLabel.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        executionValueLabel.setForeground(new java.awt.Color(51, 255, 0));
        executionValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        executionValueLabel.setText("106%");

        javax.swing.GroupLayout planExecutionPanelLayout = new javax.swing.GroupLayout(planExecutionPanel);
        planExecutionPanel.setLayout(planExecutionPanelLayout);
        planExecutionPanelLayout.setHorizontalGroup(
            planExecutionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planExecutionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(planExecutionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, planExecutionPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(executionLabel))
                    .addComponent(executionValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addContainerGap())
        );
        planExecutionPanelLayout.setVerticalGroup(
            planExecutionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planExecutionPanelLayout.createSequentialGroup()
                .addComponent(executionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(executionValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        apInformationPanel.add(planExecutionPanel, gridBagConstraints);

        datePanel.setBackground(new java.awt.Color(252, 254, 252));
        datePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 4, 4, new java.awt.Color(252, 254, 252)));
        datePanel.setMinimumSize(new java.awt.Dimension(220, 100));
        datePanel.setPreferredSize(new java.awt.Dimension(220, 100));

        dateLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(122, 120, 123));
        dateLabel.setText("date");

        dateValueLabel.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        dateValueLabel.setForeground(new java.awt.Color(120, 120, 123));
        dateValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateValueLabel.setText("2016-11-14");
        dateValueLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout datePanelLayout = new javax.swing.GroupLayout(datePanel);
        datePanel.setLayout(datePanelLayout);
        datePanelLayout.setHorizontalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dateLabel))
                    .addComponent(dateValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap())
        );
        datePanelLayout.setVerticalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datePanelLayout.createSequentialGroup()
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        apInformationPanel.add(datePanel, gridBagConstraints);

        filterLabelPanel.setBackground(new java.awt.Color(230, 231, 234));
        filterLabelPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 2, new java.awt.Color(252, 254, 252)));
        filterLabelPanel.setMaximumSize(new java.awt.Dimension(164, 50));
        filterLabelPanel.setMinimumSize(new java.awt.Dimension(100, 50));
        filterLabelPanel.setPreferredSize(new java.awt.Dimension(164, 50));
        filterLabelPanel.setLayout(new java.awt.BorderLayout());

        filterLabel.setBackground(new java.awt.Color(230, 231, 234));
        filterLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        filterLabel.setForeground(new java.awt.Color(122, 120, 123));
        filterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filterLabel.setText("Filter by");
        filterLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        filterLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filterLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filterLabel.setIconTextGap(0);
        filterLabel.setMaximumSize(new java.awt.Dimension(164, 24));
        filterLabel.setMinimumSize(new java.awt.Dimension(80, 24));
        filterLabel.setOpaque(true);
        filterLabel.setPreferredSize(new java.awt.Dimension(100, 24));
        filterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                filterLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                filterLabelMouseExited(evt);
            }
        });
        filterLabelPanel.add(filterLabel, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        apInformationPanel.add(filterLabelPanel, gridBagConstraints);

        statusPanel.setBackground(new java.awt.Color(0, 66, 118));
        statusPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 2, 4, 0, new java.awt.Color(252, 254, 252)));
        statusPanel.setMaximumSize(new java.awt.Dimension(32767, 50));
        statusPanel.setMinimumSize(new java.awt.Dimension(710, 50));
        statusPanel.setPreferredSize(new java.awt.Dimension(710, 50));

        statusRadioButton.setBackground(new java.awt.Color(0, 66, 118));
        statusRadioButton.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        statusRadioButton.setForeground(new java.awt.Color(252, 254, 252));
        statusRadioButton.setSelected(true);
        statusRadioButton.setIconTextGap(0);
        statusRadioButton.setMargin(new java.awt.Insets(0, 2, 0, 2));
        statusRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusRadioButtonActionPerformed(evt);
            }
        });
        statusPanel.add(statusRadioButton);

        statusComboBox.setBackground(new java.awt.Color(252, 254, 252));
        statusComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        statusComboBox.setForeground(new java.awt.Color(48, 49, 50));
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  --- Select ---", "Completed", "Overdue", "In Process", "Completed APP", "Near to Due Date", "Waiting to Start" }));
        statusComboBox.setBorder(null);
        statusComboBox.setMaximumSize(new java.awt.Dimension(149, 29));
        statusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboBoxActionPerformed(evt);
            }
        });
        statusPanel.add(statusComboBox);

        status2Label.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        status2Label.setForeground(new java.awt.Color(252, 254, 252));
        status2Label.setText("status");
        statusPanel.add(status2Label);

        dateRadioButton.setBackground(new java.awt.Color(0, 66, 118));
        dateRadioButton.setForeground(new java.awt.Color(252, 254, 252));
        dateRadioButton.setSelected(true);
        dateRadioButton.setIconTextGap(0);
        dateRadioButton.setMargin(new java.awt.Insets(0, 2, 0, 2));
        dateRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateRadioButtonActionPerformed(evt);
            }
        });
        statusPanel.add(dateRadioButton);

        dateComboBox.setBackground(new java.awt.Color(252, 254, 252));
        dateComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        dateComboBox.setForeground(new java.awt.Color(48, 49, 50));
        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "start Date", "due Date", "end Date" }));
        dateComboBox.setBorder(null);
        dateComboBox.setMaximumSize(new java.awt.Dimension(106, 29));
        dateComboBox.setMinimumSize(new java.awt.Dimension(90, 29));
        statusPanel.add(dateComboBox);

        date2Label.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        date2Label.setForeground(new java.awt.Color(252, 254, 252));
        date2Label.setText("date");
        statusPanel.add(date2Label);

        ownerRadioButton.setBackground(new java.awt.Color(6, 66, 118));
        ownerRadioButton.setIconTextGap(0);
        ownerRadioButton.setMargin(new java.awt.Insets(0, 2, 0, 0));
        ownerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerRadioButtonActionPerformed(evt);
            }
        });
        statusPanel.add(ownerRadioButton);

        owner2Label.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        owner2Label.setForeground(new java.awt.Color(252, 254, 252));
        owner2Label.setText("owner");
        statusPanel.add(owner2Label);

        owner2TextField.setBackground(new java.awt.Color(252, 254, 252));
        owner2TextField.setText("acronym");
        owner2TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 1, 1, new java.awt.Color(252, 254, 252)));
        owner2TextField.setMinimumSize(new java.awt.Dimension(4, 27));
        owner2TextField.setPreferredSize(new java.awt.Dimension(54, 27));
        statusPanel.add(owner2TextField);

        contentRadioButton.setBackground(new java.awt.Color(0, 66, 118));
        contentRadioButton.setIconTextGap(0);
        contentRadioButton.setMargin(new java.awt.Insets(0, 2, 0, 2));
        contentRadioButton.setMinimumSize(new java.awt.Dimension(0, 26));
        contentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentRadioButtonActionPerformed(evt);
            }
        });
        statusPanel.add(contentRadioButton);

        content2Label.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        content2Label.setForeground(new java.awt.Color(252, 254, 252));
        content2Label.setText("content");
        content2Label.setMinimumSize(new java.awt.Dimension(0, 15));
        statusPanel.add(content2Label);

        hintTextField.setBackground(new java.awt.Color(252, 254, 252));
        hintTextField.setText("hint");
        hintTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 1, 1, new java.awt.Color(252, 254, 252)));
        hintTextField.setMinimumSize(new java.awt.Dimension(0, 27));
        hintTextField.setPreferredSize(new java.awt.Dimension(35, 27));
        statusPanel.add(hintTextField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        apInformationPanel.add(statusPanel, gridBagConstraints);

        buttonsPanel.setBackground(new java.awt.Color(0, 66, 118));
        buttonsPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 4, 2, new java.awt.Color(252, 254, 252)));
        buttonsPanel.setMaximumSize(new java.awt.Dimension(122, 50));
        buttonsPanel.setMinimumSize(new java.awt.Dimension(120, 50));
        buttonsPanel.setPreferredSize(new java.awt.Dimension(120, 50));
        buttonsPanel.setLayout(new javax.swing.BoxLayout(buttonsPanel, javax.swing.BoxLayout.LINE_AXIS));

        addIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plusWhite24.png"))); // NOI18N
        addIcon.setToolTipText("Add Action");
        addIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addIcon.setIconTextGap(0);
        addIcon.setMaximumSize(new java.awt.Dimension(32767, 40));
        addIcon.setMinimumSize(new java.awt.Dimension(35, 40));
        addIcon.setPreferredSize(new java.awt.Dimension(35, 40));
        buttonsPanel.add(addIcon);

        editIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editWhite24.png"))); // NOI18N
        editIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editIcon.setIconTextGap(0);
        editIcon.setMaximumSize(new java.awt.Dimension(32767, 40));
        editIcon.setMinimumSize(new java.awt.Dimension(34, 40));
        editIcon.setPreferredSize(new java.awt.Dimension(34, 40));
        buttonsPanel.add(editIcon);

        deleteIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteWhite24.png"))); // NOI18N
        deleteIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteIcon.setIconTextGap(0);
        deleteIcon.setMaximumSize(new java.awt.Dimension(32767, 40));
        deleteIcon.setMinimumSize(new java.awt.Dimension(34, 40));
        deleteIcon.setPreferredSize(new java.awt.Dimension(34, 40));
        buttonsPanel.add(deleteIcon);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        apInformationPanel.add(buttonsPanel, gridBagConstraints);

        getContentPane().add(apInformationPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboBoxActionPerformed

    private void statusRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusRadioButtonActionPerformed

    private void dateRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateRadioButtonActionPerformed

    private void ownerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerRadioButtonActionPerformed

    private void contentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contentRadioButtonActionPerformed

    private void filterLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterLabelMouseEntered
        filterLabel.setBackground(Color.decode("#D9DADC"));
    }//GEN-LAST:event_filterLabelMouseEntered

    private void filterLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterLabelMouseExited
        filterLabel.setBackground(Color.decode("#E6E7EA"));
    }//GEN-LAST:event_filterLabelMouseExited

    private void dotMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotMenuLabelMouseClicked
        int xPos = meetingPopupMenu.getPreferredSize().width - 3;
        meetingPopupMenu.show(dotMenuLabel, -xPos, -5);
    }//GEN-LAST:event_dotMenuLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException {
        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionLabel;
    private javax.swing.JLabel actionValueLabel;
    private javax.swing.JLabel actionsLabel;
    private javax.swing.JLabel addIcon;
    private javax.swing.JPanel apInformationPanel;
    private javax.swing.JPanel apPanel;
    private javax.swing.JPanel appActionPanel;
    private javax.swing.JLabel appLabel;
    private javax.swing.JLabel appValueLabel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel completedActionPanel;
    private javax.swing.JLabel completedLabel;
    private javax.swing.JLabel completedValueLabel;
    private javax.swing.JLabel content2Label;
    private javax.swing.JRadioButton contentRadioButton;
    private javax.swing.JLabel date2Label;
    private javax.swing.JComboBox<String> dateComboBox;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel datePanel;
    private javax.swing.JRadioButton dateRadioButton;
    private javax.swing.JLabel dateValueLabel;
    private javax.swing.JLabel deleteIcon;
    private javax.swing.JLabel dotMenuLabel;
    private javax.swing.JLabel editIcon;
    private javax.swing.JLabel executionLabel;
    private javax.swing.JLabel executionValueLabel;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JPanel filterLabelPanel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField hintTextField;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel meetingLabel;
    private javax.swing.JPanel meetingNamePanel;
    private javax.swing.JPopupMenu meetingPopupMenu;
    private javax.swing.JPanel overdueActionPanel;
    private javax.swing.JLabel overdueLabel;
    private javax.swing.JLabel overdueValueLabel;
    private javax.swing.JLabel owner2Label;
    private javax.swing.JTextField owner2TextField;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JPanel ownerNamePanel;
    private javax.swing.JRadioButton ownerRadioButton;
    private javax.swing.JLabel participantsLabel;
    private javax.swing.JPanel participantsPanel;
    private javax.swing.JTextArea participantsTextArea;
    private javax.swing.JLabel performanceLabel;
    private javax.swing.JLabel performanceValueLabel;
    private javax.swing.JPanel planExecutionPanel;
    private javax.swing.JLabel planLabel;
    private javax.swing.JScrollPane scrollParticipants;
    private javax.swing.JLabel status2Label;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JRadioButton statusRadioButton;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JPanel teamPerformancePanel;
    private javax.swing.JLabel title1Label;
    private javax.swing.JLabel title2Label;
    private javax.swing.JPanel totalActionsPanel;
    // End of variables declaration//GEN-END:variables
}
